language: java
os:
  - linux
  - osx
dist: bionic
osx_image: xcode11.3
jdk:
  - openjdk8
  - oraclejdk11
  - openjdk11
addons:
  apt:
    packages:
      - ant
      - ant-optional
  homebrew:
    # https://travis-ci.community/t/macos-build-fails-because-of-homebrew-bundle-unknown-command/7296
    update: true
    packages:
      - ant
jobs:
  include:
    - os: linux
      dist: trusty
      jdk: oraclejdk8
    - os: osx
      osx_image: xcode9.3
      jdk: oraclejdk8
    # - os: osx
    #   osx_image: xcode9.3
    #   jdk: openjdk8
  exclude:
    - os: osx
      osx_image: xcode11.3
      jdk: openjdk8
script:
  - ant jar
  - ant doc
after_success:
  - ant test
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build/doc/
  committer_from_gh: true
  on:
    branch: master
    os: linux
    jdk: openjdk8
